-- ============================================================
-- HouseFound — Esquema de base de datos (versión reforzada)
-- Incluye: FKs correctas, CHECK constraints de reglas de negocio,
-- restricciones de unicidad compuestas, índices de rendimiento
-- y políticas ON DELETE explícitas.
-- ============================================================

-- ---------- TABLAS ----------

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "rol" varchar NOT NULL,
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_usuarios_rol CHECK ("rol" IN ('adoptante', 'refugio'))
);

CREATE TABLE "refugios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "nombre_refugio" varchar NOT NULL,
  "direccion" varchar,
  "telefono_contacto" varchar
);

CREATE TABLE "perfiles_adoptante" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "espacio_disponible" varchar,
  "tiempo_disponible_horas_dia" integer,
  "experiencia_previa" varchar,
  "tiene_ninos" boolean NOT NULL DEFAULT false,
  "otras_mascotas" boolean NOT NULL DEFAULT false,
  "nivel_actividad_fisica" varchar,
  CONSTRAINT chk_perfil_espacio CHECK ("espacio_disponible" IN ('departamento', 'casa_patio', 'casa_grande')),
  CONSTRAINT chk_perfil_experiencia CHECK ("experiencia_previa" IN ('ninguna', 'basica', 'alta')),
  CONSTRAINT chk_perfil_actividad CHECK ("nivel_actividad_fisica" IN ('bajo', 'medio', 'alto')),
  CONSTRAINT chk_perfil_horas CHECK ("tiempo_disponible_horas_dia" BETWEEN 0 AND 24)
);

CREATE TABLE "mascotas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "refugio_id" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "especie" varchar,
  "raza" varchar,
  "edad" integer,
  "nivel_energia" varchar,
  "nivel_socializacion" varchar,
  "compatible_ninos" boolean,
  "compatible_otras_mascotas" boolean,
  "nivel_experiencia_requerida" varchar,
  "espacio_minimo_requerido" varchar,
  "estado" varchar NOT NULL DEFAULT 'disponible',
  "fecha_publicacion" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_mascota_edad CHECK ("edad" IS NULL OR "edad" >= 0),
  CONSTRAINT chk_mascota_energia CHECK ("nivel_energia" IN ('bajo', 'medio', 'alto')),
  CONSTRAINT chk_mascota_socializacion CHECK ("nivel_socializacion" IN ('bajo', 'medio', 'alto')),
  CONSTRAINT chk_mascota_experiencia_req CHECK ("nivel_experiencia_requerida" IN ('bajo', 'medio', 'alto')),
  CONSTRAINT chk_mascota_espacio_min CHECK ("espacio_minimo_requerido" IN ('departamento', 'casa_patio', 'casa_grande')),
  CONSTRAINT chk_mascota_estado CHECK ("estado" IN ('disponible', 'en_proceso', 'adoptada'))
);

CREATE TABLE "fotos_mascota" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mascota_id" integer NOT NULL,
  "url" varchar NOT NULL,
  "es_principal" boolean NOT NULL DEFAULT false,
  "orden" integer,
  CONSTRAINT chk_foto_orden CHECK ("orden" IS NULL OR "orden" >= 0)
);

CREATE TABLE "matches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adoptante_id" integer NOT NULL,
  "mascota_id" integer NOT NULL,
  "score_compatibilidad" numeric(4,3),
  "fecha_calculo" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_match_score CHECK ("score_compatibilidad" IS NULL OR "score_compatibilidad" BETWEEN 0 AND 1),
  CONSTRAINT uq_match_adoptante_mascota UNIQUE ("adoptante_id", "mascota_id")
);

CREATE TABLE "postulaciones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adoptante_id" integer NOT NULL,
  "mascota_id" integer NOT NULL,
  "estado" varchar NOT NULL DEFAULT 'pendiente',
  "fecha_postulacion" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_postulacion_estado CHECK ("estado" IN ('pendiente', 'aprobada', 'rechazada'))
);

CREATE TABLE "seguimientos_post_adopcion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postulacion_id" integer NOT NULL,
  "dias_transcurridos" integer NOT NULL,
  "resultado" varchar,
  "motivo_devolucion" text,
  "fecha_respuesta" timestamp,
  CONSTRAINT chk_seguimiento_dias CHECK ("dias_transcurridos" IN (30, 90)),
  CONSTRAINT chk_seguimiento_resultado CHECK ("resultado" IN ('exitosa', 'devuelta', 'en_proceso')),
  CONSTRAINT uq_seguimiento_postulacion_hito UNIQUE ("postulacion_id", "dias_transcurridos")
);

-- ---------- COMENTARIOS DE DOCUMENTACIÓN ----------

COMMENT ON COLUMN "usuarios"."password_hash" IS 'Nunca se guarda la contraseña en texto plano, solo su hash con bcrypt';
COMMENT ON COLUMN "usuarios"."rol" IS 'adoptante | refugio (forzado por CHECK)';
COMMENT ON COLUMN "refugios"."usuario_id" IS 'Relación 1 a 1 con usuarios';
COMMENT ON COLUMN "perfiles_adoptante"."usuario_id" IS 'Relación 1 a 1 con usuarios';
COMMENT ON COLUMN "fotos_mascota"."url" IS 'URL de Cloudinary';
COMMENT ON COLUMN "matches"."score_compatibilidad" IS 'Entre 0 y 1, con 3 decimales de precisión';

-- ---------- FOREIGN KEYS con política ON DELETE explícita ----------
-- Perfiles/roles: si se borra el usuario, se borra su perfil (dato dependiente 1-1)
ALTER TABLE "refugios"
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfiles_adoptante"
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- Mascotas: NO se permite borrar un refugio si tiene mascotas publicadas
-- (evita perder historial de negocio por accidente; usar "estado" para dar de baja)
ALTER TABLE "mascotas"
  ADD FOREIGN KEY ("refugio_id") REFERENCES "refugios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

-- Fotos: si se borra la mascota, sus fotos no tienen razón de existir
ALTER TABLE "fotos_mascota"
  ADD FOREIGN KEY ("mascota_id") REFERENCES "mascotas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- Matches/Postulaciones/Seguimientos: son evidencia histórica del negocio,
-- no deben desaparecer aunque el perfil o la mascota se den de baja después
ALTER TABLE "matches"
  ADD FOREIGN KEY ("adoptante_id") REFERENCES "perfiles_adoptante" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "matches"
  ADD FOREIGN KEY ("mascota_id") REFERENCES "mascotas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "postulaciones"
  ADD FOREIGN KEY ("adoptante_id") REFERENCES "perfiles_adoptante" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "postulaciones"
  ADD FOREIGN KEY ("mascota_id") REFERENCES "mascotas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimientos_post_adopcion"
  ADD FOREIGN KEY ("postulacion_id") REFERENCES "postulaciones" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

-- ---------- ÍNDICES DE RENDIMIENTO ----------
-- Postgres NO indexa automáticamente las columnas FK (solo las PK y UNIQUE).
-- Estas se consultan constantemente en joins y filtros del Matching/Postulaciones/Dashboard.

CREATE INDEX idx_mascotas_refugio_id ON "mascotas" ("refugio_id");
CREATE INDEX idx_mascotas_estado ON "mascotas" ("estado");
CREATE INDEX idx_fotos_mascota_mascota_id ON "fotos_mascota" ("mascota_id");
CREATE INDEX idx_matches_adoptante_id ON "matches" ("adoptante_id");
CREATE INDEX idx_matches_mascota_id ON "matches" ("mascota_id");
CREATE INDEX idx_postulaciones_adoptante_id ON "postulaciones" ("adoptante_id");
CREATE INDEX idx_postulaciones_mascota_id ON "postulaciones" ("mascota_id");
CREATE INDEX idx_postulaciones_estado ON "postulaciones" ("estado");
CREATE INDEX idx_seguimientos_postulacion_id ON "seguimientos_post_adopcion" ("postulacion_id");

-- ---------- REGLA DE NEGOCIO ADICIONAL: una sola postulación activa por par ----------
-- No se bloquea con UNIQUE simple porque SÍ debe poder re-postular después de un rechazo.
-- Un índice único parcial permite exactamente 1 postulación "pendiente" por (adoptante, mascota),
-- pero no limita cuántas "rechazadas" existan en el historial.
CREATE UNIQUE INDEX uq_postulacion_pendiente_por_par
  ON "postulaciones" ("adoptante_id", "mascota_id")
  WHERE "estado" = 'pendiente';

-- ---------- REGLA DE NEGOCIO ADICIONAL: una sola foto principal por mascota ----------
-- No limita el carrusel: el carrusel del frontend debe mostrar TODAS las fotos de
-- fotos_mascota ordenadas por "orden", sin filtrar por es_principal. Este índice
-- solo evita que dos fotos queden marcadas como portada/miniatura simultáneamente
-- (ej. bug de doble clic o carga concurrente al subir fotos).
CREATE UNIQUE INDEX uq_foto_principal_por_mascota
  ON "fotos_mascota" ("mascota_id")
  WHERE "es_principal" = true;

-- ---------- NOTA PARA EL BACKEND (auth-service) — NO requiere cambio de esquema ----------
-- El email en "usuarios" es UNIQUE pero Postgres compara case-sensitive por defecto,
-- por lo que "Juan@mail.com" y "juan@mail.com" se consideran distintos y el UNIQUE
-- no los detecta como duplicados. Decisión: normalizar el email a minúsculas en el
-- backend (auth-service), en el endpoint de registro y de login, ANTES de guardar
-- o de consultar contra la BD. No se usa la extensión citext para mantener el
-- esquema simple y portable entre entornos.
