-- ============================================================
-- HouseFound — Esquema de base de datos (versión reforzada)
-- Incluye: FKs correctas, CHECK constraints de reglas de negocio,
-- restricciones de unicidad compuestas, índices de rendimiento
-- y políticas ON DELETE explícitas.
-- ============================================================

-- ---------- TABLAS ----------

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  -- email y password_hash son NULL en refugios: entran con RUT + código y su
  -- correo vive en organizaciones_validadas.
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "rol" varchar NOT NULL,
  "estado" varchar NOT NULL DEFAULT 'activo',
  "fecha_registro" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_usuarios_rol CHECK ("rol" IN ('adoptante', 'refugio')),
  CONSTRAINT chk_usuarios_estado CHECK ("estado" IN ('pendiente', 'activo')),
  CONSTRAINT chk_usuarios_credenciales_adoptante
    CHECK ("rol" = 'refugio' OR ("email" IS NOT NULL AND "password_hash" IS NOT NULL))
);

CREATE TABLE "refugios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "nombre_refugio" varchar NOT NULL,
  "direccion" varchar,
  -- Opcional a nivel de BD (perfiles antiguos pueden no tenerlo), pero la
  -- API exige completarlo al guardar el perfil: se usa para el botón de
  -- WhatsApp que coordina la entrega una vez aprobada una postulación.
  "telefono_contacto" varchar,
  "organizacion_id" integer UNIQUE NOT NULL
);

-- Cuestionario del adoptante: las respuestas son NULL hasta que lo completa
-- (el registro crea el perfil solo con el teléfono). Cómo se usa cada una en
-- el matching: Aplicación/backend/matching-service/scoring.py.
CREATE TABLE "perfiles_adoptante" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "espacio_disponible" varchar,
  "restriccion_vivienda" varchar,
  "horas_sola" varchar,
  "tiempo_actividad" varchar,
  "experiencia_previa" varchar,
  "ambiente_hogar" varchar,
  "ninos_hogar" varchar,
  "tiene_perros" boolean NOT NULL DEFAULT false,
  "tiene_gatos" boolean NOT NULL DEFAULT false,
  "alergias" varchar,
  "acepta_cuidados" varchar,
  -- Preferencias, NULL = me da igual: la especie filtra las recomendaciones;
  -- tamaño, etapa de vida y sexo solo las ordenan.
  "especie_preferida" varchar,
  "tamanos_preferidos" varchar[],
  "etapas_preferidas" varchar[],
  "sexo_preferido" varchar,
  -- Mismo criterio que telefono_contacto en refugios: opcional en la BD,
  -- obligatorio en la API para perfiles nuevos.
  "telefono" varchar,
  "foto_perfil" varchar,
  CONSTRAINT chk_perfil_espacio CHECK ("espacio_disponible" IN ('departamento', 'casa_patio', 'casa_grande')),
  CONSTRAINT chk_perfil_restriccion_vivienda
    CHECK ("restriccion_vivienda" IN ('ninguna', 'solo_pequenas', 'solo_gatos', 'no_se')),
  CONSTRAINT chk_perfil_horas_sola CHECK ("horas_sola" IN ('menos_2h', '2_4h', '4_8h', 'mas_8h')),
  CONSTRAINT chk_perfil_tiempo_actividad CHECK ("tiempo_actividad" IN ('menos_30m', '30_60m', 'mas_60m')),
  CONSTRAINT chk_perfil_experiencia CHECK ("experiencia_previa" IN ('ninguna', 'basica', 'alta')),
  CONSTRAINT chk_perfil_ambiente CHECK ("ambiente_hogar" IN ('tranquilo', 'moderado', 'movido')),
  CONSTRAINT chk_perfil_ninos CHECK ("ninos_hogar" IN ('no', 'mayores', 'pequenos')),
  CONSTRAINT chk_perfil_alergias CHECK ("alergias" IN ('ninguna', 'perros', 'gatos', 'ambos')),
  CONSTRAINT chk_perfil_acepta_cuidados CHECK ("acepta_cuidados" IN ('no', 'leves', 'complejos')),
  CONSTRAINT chk_perfil_especie_preferida CHECK ("especie_preferida" IS NULL OR "especie_preferida" IN ('Perro', 'Gato')),
  CONSTRAINT chk_perfil_tamanos_preferidos
    CHECK ("tamanos_preferidos" IS NULL OR "tamanos_preferidos" <@ ARRAY['pequeno', 'mediano', 'grande']::varchar[]),
  CONSTRAINT chk_perfil_etapas_preferidas
    CHECK ("etapas_preferidas" IS NULL OR "etapas_preferidas" <@ ARRAY['cachorro', 'joven', 'adulto', 'senior']::varchar[]),
  CONSTRAINT chk_perfil_sexo_preferido CHECK ("sexo_preferido" IS NULL OR "sexo_preferido" IN ('macho', 'hembra'))
);

CREATE TABLE "mascotas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "refugio_id" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "especie" varchar NOT NULL,
  "raza" varchar,
  "edad" integer NOT NULL,
  "sexo" varchar NOT NULL,
  "tamano" varchar,
  -- Cuestionario de compatibilidad: cada respuesta se compara con su par del adoptante.
  "espacio_minimo_requerido" varchar NOT NULL,
  "tolerancia_soledad" varchar NOT NULL,
  "nivel_energia" varchar NOT NULL,
  "nivel_experiencia_requerida" varchar NOT NULL,
  "temperamento" varchar NOT NULL,
  -- Convivencia: NULL = no evaluado (genera una alerta, nunca excluye).
  "convivencia_ninos" varchar,
  "convive_perros" boolean,
  "convive_gatos" boolean,
  "nivel_cuidados" varchar NOT NULL,
  "cuidados_especiales" text,
  -- Ficha de salud: informativa, no puntúa (NULL = sin información).
  "esterilizado" boolean,
  "vacunas_al_dia" boolean,
  "desparasitado" boolean,
  "microchip" boolean,
  "notas_salud" text,
  "estado" varchar NOT NULL DEFAULT 'disponible',
  "fecha_publicacion" timestamp NOT NULL DEFAULT (now()),
  -- 'seed' = dato de ejemplo generado por script; clave_seed permite recargar sin duplicar.
  "origen" varchar NOT NULL DEFAULT 'manual',
  "clave_seed" varchar,
  CONSTRAINT uq_mascota_clave_seed UNIQUE ("clave_seed"),
  CONSTRAINT chk_mascota_origen CHECK ("origen" IN ('manual', 'seed')),
  CONSTRAINT chk_mascota_seed_con_clave CHECK (("origen" = 'seed') = ("clave_seed" IS NOT NULL)),
  CONSTRAINT chk_mascota_especie CHECK ("especie" IN ('Perro', 'Gato')),
  CONSTRAINT chk_mascota_edad CHECK ("edad" IS NULL OR "edad" >= 0),
  CONSTRAINT chk_mascota_sexo CHECK ("sexo" IN ('macho', 'hembra')),
  CONSTRAINT chk_mascota_tamano CHECK ("tamano" IN ('pequeno', 'mediano', 'grande')),
  -- Tamaño adulto estimado: obligatorio en perros, no aplica a gatos.
  CONSTRAINT chk_mascota_tamano_perro CHECK (("especie" = 'Perro') = ("tamano" IS NOT NULL)),
  CONSTRAINT chk_mascota_espacio_min CHECK ("espacio_minimo_requerido" IN ('departamento', 'casa_patio', 'casa_grande')),
  CONSTRAINT chk_mascota_tolerancia_soledad
    CHECK ("tolerancia_soledad" IN ('menos_2h', '2_4h', '4_8h', 'mas_8h')),
  CONSTRAINT chk_mascota_energia CHECK ("nivel_energia" IN ('bajo', 'medio', 'alto')),
  CONSTRAINT chk_mascota_experiencia_req CHECK ("nivel_experiencia_requerida" IN ('bajo', 'medio', 'alto')),
  CONSTRAINT chk_mascota_temperamento CHECK ("temperamento" IN ('sociable', 'reservado', 'timido')),
  CONSTRAINT chk_mascota_convivencia_ninos CHECK ("convivencia_ninos" IN ('todos', 'mayores', 'no')),
  CONSTRAINT chk_mascota_nivel_cuidados CHECK ("nivel_cuidados" IN ('ninguno', 'leves', 'complejos')),
  -- Si necesita cuidados, el refugio debe describirlos.
  CONSTRAINT chk_mascota_cuidados_descritos
    CHECK ("nivel_cuidados" = 'ninguno' OR coalesce(length(trim("cuidados_especiales")), 0) > 0),
  CONSTRAINT chk_mascota_estado CHECK ("estado" IN ('disponible', 'en_proceso', 'adoptada'))
);

CREATE TABLE "fotos_mascota" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mascota_id" integer NOT NULL,
  "url" varchar NOT NULL,
  "es_principal" boolean NOT NULL DEFAULT false,
  "orden" integer,
  CONSTRAINT chk_foto_orden CHECK ("orden" IS NULL OR "orden" >= 0)
);

CREATE TABLE "matches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adoptante_id" integer NOT NULL,
  "mascota_id" integer NOT NULL,
  "score_compatibilidad" numeric(4,3),
  "desglose" jsonb,
  "fecha_calculo" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_match_score CHECK ("score_compatibilidad" IS NULL OR "score_compatibilidad" BETWEEN 0 AND 1),
  CONSTRAINT uq_match_adoptante_mascota UNIQUE ("adoptante_id", "mascota_id")
);

CREATE TABLE "postulaciones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adoptante_id" integer NOT NULL,
  "mascota_id" integer NOT NULL,
  "estado" varchar NOT NULL DEFAULT 'pendiente',
  "fecha_postulacion" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_postulacion_estado CHECK ("estado" IN ('pendiente', 'aprobada', 'rechazada'))
);

CREATE TABLE "seguimientos_post_adopcion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postulacion_id" integer NOT NULL,
  "dias_transcurridos" integer NOT NULL,
  "resultado" varchar,
  "motivo_devolucion" text,
  "fecha_respuesta" timestamp,
  CONSTRAINT chk_seguimiento_dias CHECK ("dias_transcurridos" IN (30, 90)),
  CONSTRAINT chk_seguimiento_resultado CHECK ("resultado" IN ('exitosa', 'devuelta', 'en_proceso')),
  CONSTRAINT uq_seguimiento_postulacion_hito UNIQUE ("postulacion_id", "dias_transcurridos")
);

-- Nómina SII de organizaciones habilitadas para operar como refugio
-- (ver migraciones/001_organizaciones_validadas.sql para BD existentes).
CREATE TABLE "organizaciones_validadas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rut" integer UNIQUE NOT NULL,
  "dv" char(1) NOT NULL,
  "razon_social" varchar NOT NULL,
  "actividad" text,
  "unidad_sii" varchar,
  "direccion" varchar,
  "comuna" varchar,
  "region" varchar,
  "fecha_inscripcion" date,
  "correo" varchar,
  "es_prueba" boolean NOT NULL DEFAULT false,
  "fecha_carga" timestamp NOT NULL DEFAULT (now()),
  "fecha_actualizacion" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_org_rut CHECK ("rut" > 0),
  CONSTRAINT chk_org_dv CHECK ("dv" IN ('0','1','2','3','4','5','6','7','8','9','K')),
  CONSTRAINT chk_org_correo_minusculas CHECK ("correo" IS NULL OR "correo" = lower("correo"))
);

-- Códigos del login institucional (un solo uso, con vencimiento).
CREATE TABLE "codigos_verificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "codigo_hash" varchar NOT NULL,
  "expira_en" timestamp NOT NULL,
  "intentos" integer NOT NULL DEFAULT 0,
  "usado" boolean NOT NULL DEFAULT false,
  "creado_en" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_codigo_intentos CHECK ("intentos" >= 0)
);

-- ---------- COMENTARIOS DE DOCUMENTACIÓN ----------

COMMENT ON COLUMN "usuarios"."password_hash" IS 'Nunca se guarda la contraseña en texto plano, solo su hash con bcrypt';
COMMENT ON COLUMN "usuarios"."rol" IS 'adoptante | refugio (forzado por CHECK)';
COMMENT ON COLUMN "refugios"."usuario_id" IS 'Relación 1 a 1 con usuarios';
COMMENT ON COLUMN "perfiles_adoptante"."usuario_id" IS 'Relación 1 a 1 con usuarios';
COMMENT ON COLUMN "fotos_mascota"."url" IS 'URL de Cloudinary';
COMMENT ON COLUMN "matches"."score_compatibilidad" IS 'Entre 0 y 1, con 3 decimales de precisión';
COMMENT ON COLUMN "matches"."desglose" IS 'Detalle del cálculo: puntaje por criterio, exclusiones, alertas y preferencias no cumplidas';
COMMENT ON COLUMN "perfiles_adoptante"."restriccion_vivienda" IS 'Condiciones del arriendo o edificio: ninguna | solo_pequenas | solo_gatos | no_se. Excluye mascotas no permitidas';
COMMENT ON COLUMN "perfiles_adoptante"."horas_sola" IS 'Horas seguidas que la mascota quedaría sola en un día normal. Se compara con mascotas.tolerancia_soledad';
COMMENT ON COLUMN "perfiles_adoptante"."tiempo_actividad" IS 'Tiempo diario para pasear o jugar. Se compara con mascotas.nivel_energia';
COMMENT ON COLUMN "perfiles_adoptante"."ambiente_hogar" IS 'Calma del hogar (personas, visitas, ruido). Se compara con mascotas.temperamento';
COMMENT ON COLUMN "perfiles_adoptante"."ninos_hogar" IS 'Niños que viven o visitan seguido: no | mayores (6+) | pequenos (menores de 6). Excluye según mascotas.convivencia_ninos';
COMMENT ON COLUMN "perfiles_adoptante"."alergias" IS 'Alergia en el hogar: ninguna | perros | gatos | ambos. Excluye esa especie';
COMMENT ON COLUMN "perfiles_adoptante"."acepta_cuidados" IS 'Cuidados especiales que puede asumir: no | leves | complejos. Excluye mascotas con mayor mascotas.nivel_cuidados';
COMMENT ON COLUMN "perfiles_adoptante"."tamanos_preferidos" IS 'Preferencia (solo perros); NULL = me da igual. Ordena, no excluye';
COMMENT ON COLUMN "perfiles_adoptante"."etapas_preferidas" IS 'Preferencia de etapa de vida; NULL = me da igual. Ordena, no excluye';
COMMENT ON COLUMN "perfiles_adoptante"."sexo_preferido" IS 'Preferencia; NULL = me da igual. Ordena, no excluye';
COMMENT ON COLUMN "mascotas"."nivel_energia" IS 'Actividad diaria que necesita: bajo | medio | alto. Se compara con perfiles_adoptante.tiempo_actividad';
COMMENT ON COLUMN "mascotas"."tamano" IS 'Tamaño adulto estimado (solo perros): pequeno (hasta 10 kg) | mediano (10-25 kg) | grande (más de 25 kg)';
COMMENT ON COLUMN "mascotas"."tolerancia_soledad" IS 'Horas seguidas que puede quedarse sola tranquila. Se compara con perfiles_adoptante.horas_sola';
COMMENT ON COLUMN "mascotas"."temperamento" IS 'Relación con personas: sociable | reservado | timido (necesita un hogar tranquilo)';
COMMENT ON COLUMN "mascotas"."convivencia_ninos" IS 'todos (incluso menores de 6) | mayores (6+) | no; NULL = no evaluado (alerta, nunca excluye)';
COMMENT ON COLUMN "mascotas"."convive_perros" IS 'NULL = no evaluado (alerta, nunca excluye)';
COMMENT ON COLUMN "mascotas"."convive_gatos" IS 'NULL = no evaluado (alerta, nunca excluye)';
COMMENT ON COLUMN "mascotas"."nivel_cuidados" IS 'ninguno | leves (medicación, dieta) | complejos (enfermedad crónica, discapacidad); se describen en cuidados_especiales';
COMMENT ON COLUMN "mascotas"."notas_salud" IS 'Ficha de salud informativa (no puntúa), junto con esterilizado, vacunas_al_dia, desparasitado y microchip; NULL = sin información';

-- ---------- FOREIGN KEYS con política ON DELETE explícita ----------
-- Perfiles/roles: si se borra el usuario, se borra su perfil (dato dependiente 1-1)
ALTER TABLE "refugios"
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfiles_adoptante"
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "codigos_verificacion"
  ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") ON DELETE CASCADE;

-- Refugio -> organización de la nómina: no se puede borrar una organización con refugio.
ALTER TABLE "refugios"
  ADD CONSTRAINT fk_refugios_organizacion FOREIGN KEY ("organizacion_id")
  REFERENCES "organizaciones_validadas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

-- Mascotas: NO se permite borrar un refugio si tiene mascotas publicadas
-- (evita perder historial de negocio por accidente; usar "estado" para dar de baja)
ALTER TABLE "mascotas"
  ADD FOREIGN KEY ("refugio_id") REFERENCES "refugios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

-- Fotos: si se borra la mascota, sus fotos no tienen razón de existir
ALTER TABLE "fotos_mascota"
  ADD FOREIGN KEY ("mascota_id") REFERENCES "mascotas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- Matches/Postulaciones/Seguimientos: son evidencia histórica del negocio,
-- no deben desaparecer aunque el perfil o la mascota se den de baja después
ALTER TABLE "matches"
  ADD FOREIGN KEY ("adoptante_id") REFERENCES "perfiles_adoptante" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "matches"
  ADD FOREIGN KEY ("mascota_id") REFERENCES "mascotas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "postulaciones"
  ADD FOREIGN KEY ("adoptante_id") REFERENCES "perfiles_adoptante" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "postulaciones"
  ADD FOREIGN KEY ("mascota_id") REFERENCES "mascotas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimientos_post_adopcion"
  ADD FOREIGN KEY ("postulacion_id") REFERENCES "postulaciones" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

-- ---------- ÍNDICES DE RENDIMIENTO ----------
-- Postgres NO indexa automáticamente las columnas FK (solo las PK y UNIQUE).
-- Estas se consultan constantemente en joins y filtros del Matching/Postulaciones/Dashboard.

CREATE INDEX idx_codigos_verificacion_usuario_id ON "codigos_verificacion" ("usuario_id");
CREATE INDEX idx_mascotas_refugio_id ON "mascotas" ("refugio_id");
CREATE INDEX idx_mascotas_estado ON "mascotas" ("estado");
CREATE INDEX idx_fotos_mascota_mascota_id ON "fotos_mascota" ("mascota_id");
CREATE INDEX idx_matches_adoptante_id ON "matches" ("adoptante_id");
CREATE INDEX idx_matches_mascota_id ON "matches" ("mascota_id");
CREATE INDEX idx_postulaciones_adoptante_id ON "postulaciones" ("adoptante_id");
CREATE INDEX idx_postulaciones_mascota_id ON "postulaciones" ("mascota_id");
CREATE INDEX idx_postulaciones_estado ON "postulaciones" ("estado");
CREATE INDEX idx_seguimientos_postulacion_id ON "seguimientos_post_adopcion" ("postulacion_id");

-- ---------- REGLA DE NEGOCIO ADICIONAL: una sola postulación activa por par ----------
-- No se bloquea con UNIQUE simple porque SÍ debe poder re-postular después de un rechazo.
-- Un índice único parcial permite exactamente 1 postulación "pendiente" por (adoptante, mascota),
-- pero no limita cuántas "rechazadas" existan en el historial.
CREATE UNIQUE INDEX uq_postulacion_pendiente_por_par
  ON "postulaciones" ("adoptante_id", "mascota_id")
  WHERE "estado" = 'pendiente';

-- ---------- REGLA DE NEGOCIO ADICIONAL: una sola foto principal por mascota ----------
-- No limita el carrusel: el carrusel del frontend debe mostrar TODAS las fotos de
-- fotos_mascota ordenadas por "orden", sin filtrar por es_principal. Este índice
-- solo evita que dos fotos queden marcadas como portada/miniatura simultáneamente
-- (ej. bug de doble clic o carga concurrente al subir fotos).
CREATE UNIQUE INDEX uq_foto_principal_por_mascota
  ON "fotos_mascota" ("mascota_id")
  WHERE "es_principal" = true;

-- ---------- NOTA PARA EL BACKEND (auth-service) — NO requiere cambio de esquema ----------
-- El email en "usuarios" es UNIQUE pero Postgres compara case-sensitive por defecto,
-- por lo que "Juan@mail.com" y "juan@mail.com" se consideran distintos y el UNIQUE
-- no los detecta como duplicados. Decisión: normalizar el email a minúsculas en el
-- backend (auth-service), en el endpoint de registro y de login, ANTES de guardar
-- o de consultar contra la BD. No se usa la extensión citext para mantener el
-- esquema simple y portable entre entornos.
