-- ============================================================
-- Migración 001 — Nómina de organizaciones validadas por el SII
-- Aplicar sobre una BD existente creada con BD_HouseFound_v2.sql.
-- Es idempotente: se puede ejecutar más de una vez sin error.
-- ============================================================

CREATE TABLE IF NOT EXISTS "organizaciones_validadas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rut" integer UNIQUE NOT NULL,
  "dv" char(1) NOT NULL,
  "razon_social" varchar NOT NULL,
  "actividad" text,
  "unidad_sii" varchar,
  "direccion" varchar,
  "comuna" varchar,
  "region" varchar,
  "fecha_inscripcion" date,
  "correo" varchar,
  "es_prueba" boolean NOT NULL DEFAULT false,
  "fecha_carga" timestamp NOT NULL DEFAULT (now()),
  "fecha_actualizacion" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_org_rut CHECK ("rut" > 0),
  CONSTRAINT chk_org_dv CHECK ("dv" IN ('0','1','2','3','4','5','6','7','8','9','K')),
  CONSTRAINT chk_org_correo_minusculas CHECK ("correo" IS NULL OR "correo" = lower("correo"))
);

COMMENT ON TABLE "organizaciones_validadas" IS 'Nómina SII de instituciones sin fines de lucro de rescate animal habilitadas para operar como refugio';
COMMENT ON COLUMN "organizaciones_validadas"."rut" IS 'RUT sin DV; el DV se valida con módulo 11 al importar';
COMMENT ON COLUMN "organizaciones_validadas"."correo" IS 'Destino del código de verificación del login institucional; nunca lo ingresa el usuario';
COMMENT ON COLUMN "organizaciones_validadas"."es_prueba" IS 'true = organización ficticia del equipo para pruebas y demo, no proviene del SII';
