-- ============================================================
-- Migración 002 — Refugios ligados a la nómina SII + códigos de verificación
-- Los refugios inician sesión con RUT + código enviado al correo de la nómina,
-- sin contraseña. El correo de un refugio vive en organizaciones_validadas.
-- Idempotente: se puede ejecutar más de una vez sin error.
-- ============================================================

-- usuarios: email y contraseña pasan a ser opcionales SOLO para refugios.
ALTER TABLE "usuarios" ALTER COLUMN "email" DROP NOT NULL;
ALTER TABLE "usuarios" ALTER COLUMN "password_hash" DROP NOT NULL;

ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "estado" varchar NOT NULL DEFAULT 'activo';

ALTER TABLE "usuarios" DROP CONSTRAINT IF EXISTS chk_usuarios_estado;
ALTER TABLE "usuarios" ADD CONSTRAINT chk_usuarios_estado
  CHECK ("estado" IN ('pendiente', 'activo'));

ALTER TABLE "usuarios" DROP CONSTRAINT IF EXISTS chk_usuarios_credenciales_adoptante;
ALTER TABLE "usuarios" ADD CONSTRAINT chk_usuarios_credenciales_adoptante
  CHECK ("rol" = 'refugio' OR ("email" IS NOT NULL AND "password_hash" IS NOT NULL));

COMMENT ON COLUMN "usuarios"."estado" IS 'pendiente = cuenta de refugio creada desde la nómina, aún no verificada por código; activo = en uso';

-- refugios: cada refugio pertenece a exactamente una organización de la nómina.
ALTER TABLE "refugios" ADD COLUMN IF NOT EXISTS "organizacion_id" integer;

ALTER TABLE "refugios" DROP CONSTRAINT IF EXISTS uq_refugios_organizacion;
ALTER TABLE "refugios" ADD CONSTRAINT uq_refugios_organizacion UNIQUE ("organizacion_id");

ALTER TABLE "refugios" DROP CONSTRAINT IF EXISTS fk_refugios_organizacion;
ALTER TABLE "refugios" ADD CONSTRAINT fk_refugios_organizacion
  FOREIGN KEY ("organizacion_id") REFERENCES "organizaciones_validadas" ("id")
  ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

-- Códigos de verificación del login institucional (un solo uso, con vencimiento).
CREATE TABLE IF NOT EXISTS "codigos_verificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL REFERENCES "usuarios" ("id") ON DELETE CASCADE,
  "codigo_hash" varchar NOT NULL,
  "expira_en" timestamp NOT NULL,
  "intentos" integer NOT NULL DEFAULT 0,
  "usado" boolean NOT NULL DEFAULT false,
  "creado_en" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_codigo_intentos CHECK ("intentos" >= 0)
);

CREATE INDEX IF NOT EXISTS idx_codigos_verificacion_usuario_id ON "codigos_verificacion" ("usuario_id");

COMMENT ON COLUMN "codigos_verificacion"."codigo_hash" IS 'Nunca se guarda el código en texto plano';
